name: CI/CD Pipeline - GitHub Pages

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

permissions:
    contents: read
    actions: read
    pages: write
    id-token: write

concurrency:
    group: 'pages'
    cancel-in-progress: true

jobs:
    # =========================
    # CI
    # =========================
    ci:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Setup pnpm
              uses: pnpm/action-setup@v5
              with:
                  version: 12

            - name: Setup Node.js
              uses: actions/setup-node@v5
              with:
                  node-version: 24
                  cache: pnpm

            - name: Install Dependencies
              run: pnpm install --frozen-lockfile

            - name: Linter
              run: pnpm lint

            - name: Type check
              run: pnpm exec tsc --noEmit

            - name: Build Project
              run: pnpm build
              env:
                  # Đọc tự động các biến bạn đã add trên GitHub Settings (Variables / Secrets)
                  VITE_APP_TITLE: ${{ vars.VITE_APP_TITLE || secrets.VITE_APP_TITLE }}
                  VITE_APP_NAME: ${{ vars.VITE_APP_NAME || secrets.VITE_APP_NAME }}
                  VITE_APP_MODE: ${{ vars.VITE_APP_MODE || secrets.VITE_APP_MODE }}
                  VITE_APP_CLIENT_LOCALE: ${{ vars.VITE_APP_CLIENT_LOCALE || secrets.VITE_APP_CLIENT_LOCALE }}
                  VITE_APP_CLIENT_THEME: ${{ vars.VITE_APP_CLIENT_THEME || secrets.VITE_APP_CLIENT_THEME }}

                  VITE_APP_API_HOST: ${{ vars.VITE_APP_API_HOST || secrets.VITE_APP_API_HOST }}
                  VITE_APP_PUSHER_KEY: ${{ vars.VITE_APP_PUSHER_KEY || secrets.VITE_APP_PUSHER_KEY }}
                  VITE_APP_PUSHER_CLUSTER: ${{ vars.VITE_APP_PUSHER_CLUSTER || secrets.VITE_APP_PUSHER_CLUSTER }}

            - name: Upload dist artifact
              uses: actions/upload-artifact@v4
              with:
                  name: build-dist
                  path: ./dist
                  retention-days: 1

    # =========================
    # CD
    # =========================
    cd:
        needs: ci
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        runs-on: ubuntu-latest

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Download dist artifact
              uses: actions/download-artifact@v4
              with:
                  name: build-dist
                  path: ./dist

            - name: Setup Pages
              uses: actions/configure-pages@v5

            - name: Upload GitHub Pages artifact
              uses: actions/upload-pages-artifact@v4
              with:
                  path: ./dist

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v5
